### ISSUE TITLE
about baseline AE2-Nets

### ISSUE THREAD

**Issue by iTomxy** [XLearning-SCU/2021-CVPR-Completer#15]
AE2-Nets [1] is used as a baseline in the paper. But it seems that it's not originally designed for the **in**complete scenario. Why can it be used as a baseline ? How is it adapted for such scenario ?

---

1. Zhang C, Liu Y, Fu H. Ae2-nets: Autoencoder in autoencoder networks[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2019: 2577-2585.

**Comment by XLearning-SCU** [comment]
同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论
