### ISSUE TITLE
关于最终的embedding

### ISSUE THREAD

**Issue by weilicode** [XLearning-SCU/2021-CVPR-Completer#22]
作者您好：
    想请问一下：为什么最终聚类的embedding，对于missing modality的data sample，为什么要用predictor的输出（而不是encoder的输出）作为这些data的embedding呢？感谢解答！！

**Comment by Lin-Yijie** [comment]
我们通过预测学习去复原missing modality，用predictor网络去预测缺失的模态。例如模态2缺失，encoder只能得到模态1的embedding，通过predictor预测模态2的embedding。

**Comment by weilicode** [comment]
非常感谢，明白了
